language: scala

scala:
  - 2.12.1

jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.nvm

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

before_script:
  - mkdir -p $HOME/.sbt/launchers/$SBT_VERSION/
  - curl -L -o $HOME/.sbt/launchers/$SBT_VERSION/sbt-launch.jar http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/$SBT_VERSION/sbt-launch.jar
  - wget -O master.zip https://github.com/typelevel/sbt-tls-crossproject/archive/master.zip
  - unzip master.zip
  - rm master.zip
  - cd sbt-tls-crossproject-master
  - sbt publishLocal
  - cd ..


script:
  - sbt test
